### ISSUE TITLE
 I dont rly have a clear idea of how to configure this.

### ISSUE THREAD

**Issue by valtonngara** [EvilFreelancer/openvpn-php#2]
First of all, i do everything but in the end, php artisan command doesnt work there. On every other lumen/laravel project works, but not this one.  
The error is: **could not open input file: artisan**.
Any idea of how to go out of this situation? I tried many many many countless ways on the internet, but it didnt work a single one of them for me x(.
p.s. im new to this 🥺

**Comment by EvilFreelancer** [comment]
Hello! It looks like you are trying to execute the artisan command from outside the root of your project, try to navigate to the directory where the artisan file is located and repeat the command.

**Comment by valtonngara** [comment]
> Hello! It looks like you are trying to execute the artisan command from outside the root of your project, try to navigate to the directory where the artisan file is located and repeat the command.

Hello! 😄
First of all, thank you for your reply.
The artisan error is fixed, but the problem remains at the path that is given to us to publish.
When I publish, I get an error like this: 
**Unable to locate the publishable resources.**
**Publishing is complete**
Should I edit the path or still follow the path that is given?
Or the problem remains somewhere else?

Thank you in advance.

**Comment by EvilFreelancer** [comment]
Hm, maybe something changed in modern versions of the Laravel, which version you use?

**Comment by valtonngara** [comment]
> Hm, maybe something changed in modern versions of the Laravel, which version you use?

**The version is:**
Laravel Framework Lumen (8.2.3) (Laravel Components ^8.0)

**Comment by EvilFreelancer** [comment]
Hello! I've tested on 7.4 and 8.0 and seems everything is okay, I guess you need check your installation of Laravel (composer cache or path to the artisan).
